#!/bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start polybar
killall -q polybar
polybar main &

# BSPC monitor config
bspc monitor -d 1 2 3 4 5

# BSPC config
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Colors (Nord theme)
bspc config normal_border_color "#3B4252"
bspc config active_border_color "#4C566A"
bspc config focused_border_color "#5E81AC"
bspc config presel_feedback_color "#5E81AC"

# Rules
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a discord desktop='^5'

# Autostart
# Start picom compositor with settings from picom.conf
picom &

# Set wallpaper
feh --bg-fill $HOME/wallpapers/nord-mountains.jpg &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start nm-applet
nm-applet &

# Start notification daemon
dunst &
