#! /bin/sh
bspc monitor -d 1 2 3 4 5
bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color "#ECEFF4"
bspc config normal_border_color "#4c566a"
bspc config border_radius 10

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme spiral



# autostart programs

killall sxhkd
sxhkd &
killall picom
picom &
feh --bg-scale /home/smooth/background/wall.png
xinput set-prop 13 287 2.4
xset r rate 250 50

polybar&
qjackctl --start

termite
