#!/bin/bash

# Script to add a custom resolution to your display
# Usage: ./add-resolution.sh [width] [height] [refresh_rate]
# Example: ./add-resolution.sh 1920 1080 60

# Set default values
WIDTH=${1:-1920}
HEIGHT=${2:-1080}
REFRESH=${3:-60}

echo "🖥️ Adding custom resolution: ${WIDTH}x${HEIGHT}@${REFRESH}Hz"

# Get the primary display name
DISPLAY_NAME=$(xrandr --query | grep " connected primary" | cut -d" " -f1)

# If no primary display found, get the first connected display
if [ -z "$DISPLAY_NAME" ]; then
    DISPLAY_NAME=$(xrandr --query | grep " connected" | head -n 1 | cut -d" " -f1)
fi

if [ -z "$DISPLAY_NAME" ]; then
    echo "❌ Error: No display found!"
    exit 1
fi

echo "📺 Found display: $DISPLAY_NAME"

# Generate modeline using cvt
MODELINE=$(cvt $WIDTH $HEIGHT $REFRESH | grep Modeline | sed 's/Modeline //')

# Extract the mode name (in quotes) and the remainder of the line
MODE_NAME=$(echo $MODELINE | cut -d' ' -f1)
MODE_SETTINGS=$(echo $MODELINE | cut -d' ' -f2-)

echo "⚙️ Creating new mode: $MODE_NAME"

# Create the new mode
xrandr --newmode $MODE_NAME $MODE_SETTINGS

# Check if the operation was successful
if [ $? -ne 0 ]; then
    echo "❌ Error creating new mode!"
    exit 1
fi

echo "🔗 Adding mode to display: $DISPLAY_NAME"

# Add the mode to the display
xrandr --addmode $DISPLAY_NAME $MODE_NAME

# Check if the operation was successful
if [ $? -ne 0 ]; then
    echo "❌ Error adding mode to display!"
    exit 1
fi

echo "🚀 Switching to new resolution"

# Switch to the new mode
xrandr --output $DISPLAY_NAME --mode $MODE_NAME

# Check if the operation was successful
if [ $? -ne 0 ]; then
    echo "❌ Error switching to new mode!"
    exit 1
fi

echo "✅ Successfully set resolution to ${WIDTH}x${HEIGHT}@${REFRESH}Hz"

# Optional: Save to a file that can be included in startup scripts
echo "💾 Creating startup script: ~/.xprofile.d/custom-resolution.sh"

# Create directory if it doesn't exist
mkdir -p ~/.xprofile.d

# Create the startup script
cat > ~/.xprofile.d/custom-resolution.sh << EOF
#!/bin/bash
# Auto-generated by add-resolution.sh
xrandr --newmode $MODE_NAME $MODE_SETTINGS
xrandr --addmode $DISPLAY_NAME $MODE_NAME
xrandr --output $DISPLAY_NAME --mode $MODE_NAME
EOF

# Make the script executable
chmod +x ~/.xprofile.d/custom-resolution.sh

echo "📝 To make this resolution permanent, add this line to your ~/.xprofile or ~/.xinitrc:"
echo "   [ -d ~/.xprofile.d ] && for f in ~/.xprofile.d/*.sh; do [ -x \"\$f\" ] && . \"\$f\"; done"

exit 0